### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by thenoobtester** [jpe90/clp#11]
Hi there,

I saw this article https://jeskin.net/blog/grep-fzf-clp/ and decided to give clp a try but unfortunately I cannot compile it.

I installed this:

`apt-get install -y build-essential pkg-config luajit lua-lpeg libluajit-5.1-dev`

But when I run `make CFLAGS_LUA='-I /usr/include/luajit-2.1'`

I get :

`cc clp.c -Wall -pedantic -I /content/clp/include -I /usr/include/luajit-2.1  -DCLP_PATH=\"/clp\" -DSRC_LUA_PATH=\"/lua\"   -o clp
/tmp/ccMB4BAC.o: In function `bail':
clp.c:(.text+0xcbc): undefined reference to `lua_tolstring'
/tmp/ccMB4BAC.o: In function `print_lua_path':
clp.c:(.text+0xd0c): undefined reference to `lua_getfield'
clp.c:(.text+0xd24): undefined reference to `lua_getfield'
clp.c:(.text+0xd3a): undefined reference to `lua_tolstring'
/tmp/ccMB4BAC.o: In function `lua_path_add':
clp.c:(.text+0xd91): undefined reference to `lua_getfield'
clp.c:(.text+0xda4): undefined reference to `lua_pushstring'
clp.c:(.text+0xdb7): undefined reference to `lua_pushstring'
clp.c:(.text+0xdcf): undefined reference to `lua_getfield'
clp.c:(.text+0xde0): undefined reference to `lua_concat'
clp.c:(.text+0xdf8): undefined reference to `lua_setfield'
clp.c:(.text+0xe09): undefined reference to `lua_settop'
/tmp/ccMB4BAC.o: In function `lua_paths_get':
clp.c:(.text+0xe4d): undefined reference to `lua_getfield'
clp.c:(.text+0xe65): undefined reference to `lua_getfield'
clp.c:(.text+0xe7b): undefined reference to `lua_tolstring'
clp.c:(.text+0xebb): undefined reference to `lua_getfield'
clp.c:(.text+0xed1): undefined reference to `lua_tolstring'
/tmp/ccMB4BAC.o: In function `package_exists':
clp.c:(.text+0x109e): undefined reference to `luaL_loadstring'
clp.c:(.text+0x10c5): undefined reference to `lua_pushstring'
clp.c:(.text+0x10e3): undefined reference to `lua_pcall'
clp.c:(.text+0x10fb): undefined reference to `lua_toboolean'
clp.c:(.text+0x112c): undefined reference to `lua_settop'
/tmp/ccMB4BAC.o: In function `main':
clp.c:(.text+0x1229): undefined reference to `luaL_newstate'
clp.c:(.text+0x1253): undefined reference to `luaL_openlibs'
clp.c:(.text+0x1422): undefined reference to `lua_getfield'
clp.c:(.text+0x1438): undefined reference to `lua_pushstring'
clp.c:(.text+0x1456): undefined reference to `lua_pcall'
clp.c:(.text+0x147e): undefined reference to `lua_tolstring'
clp.c:(.text+0x14b7): undefined reference to `lua_getfield'
clp.c:(.text+0x14d0): undefined reference to `lua_createtable'
clp.c:(.text+0x155b): undefined reference to `lua_getfield'
clp.c:(.text+0x1579): undefined reference to `lua_pcall'
clp.c:(.text+0x15a1): undefined reference to `lua_tolstring'
clp.c:(.text+0x15d8): undefined reference to `lua_close'
clp.c:(.text+0x160b): undefined reference to `lua_pushlstring'
clp.c:(.text+0x1624): undefined reference to `lua_pushstring'
clp.c:(.text+0x1638): undefined reference to `lua_settable'
clp.c:(.text+0x166a): undefined reference to `lua_pushlstring'
clp.c:(.text+0x1685): undefined reference to `lua_pushinteger'
clp.c:(.text+0x1699): undefined reference to `lua_settable'
clp.c:(.text+0x171c): undefined reference to `lua_pushlstring'
clp.c:(.text+0x1735): undefined reference to `lua_pushstring'
clp.c:(.text+0x1749): undefined reference to `lua_settable'
clp.c:(.text+0x1767): undefined reference to `lua_pcall'
clp.c:(.text+0x178f): undefined reference to `lua_tolstring'
clp.c:(.text+0x17c3): undefined reference to `lua_close'
collect2: error: ld returned 1 exit status
Makefile:20: recipe for target 'clp' failed
make: *** [clp] Error 1`

My distro 18.04.6 LTS (Bionic Beaver), I also tried with liblua5.2-dev, liblua5.3-dev and get the same result.

Thank you for your help.

**Comment by jpe90** [comment]
Hi, sorry for the trouble! Did you try running `./configure` after running `apt get..`, and then just running `make`?

**Comment by thenoobtester** [comment]
It worked! Thank you for the help  and the great piece of software :)
