### ISSUE TITLE
Never loads clp.lua

### ISSUE THREAD

**Issue by Nomarian** [jpe90/clp#2]
It seems it broke on some commit.

This is if you test inside the directory, without installing

**Comment by Nomarian** [comment]
Ran a 

```
; git log a8fcb81a4891586bd7fddb00edf38830b3374515 '^'0eb0f7ce24a1025de92646245a2b6f71f21b211d | awk '/^commit/ {print $2;system("git checkout " $2 "; make;./clp config.mk")}'
```

Broken since: 88e7d0df0aded158e476ff3de86e843154d007a1

**Comment by Nomarian** [comment]
Put it back in https://github.com/Nomarian/clp/commit/656a296eab90d23efb270692fc25017a51d94760 and moved lexers outside of the lexers directory.

**Comment by jpe90** [comment]
I was wondering what that code was useful for, I figured I might find out if I removed it :)

I think the way it was implemented only worked on Linux, I can try to add it back in a way that works on other platforms when I get a chance.

**Comment by Nomarian** [comment]
freebsd also has procfs, so it should work there too.

**Comment by jpe90** [comment]
what do you think about baking the srcdir (generated by ./configure) into the executable and then loading the lua subfolder at startup like decf20da68377fd72a9fe14ebcba3a7b07a7dd86?

**Comment by Nomarian** [comment]
Seems like the right way to go? (I'm not well versed on C or autotools)


I was thinking https://github.com/Nomarian/clp/commit/f98da9f3f7e4646292c9a7b4c32f6159efe5203e, basically if ./lua/clp.lua exists, load $PWD into package.path.


but I don't like the idea of overwriting package.path if it just so happens to have lua/clp.lua... BUT I also like the idea of it.


up to you :)

**Comment by jpe90** [comment]
Yeah I have no idea what I'm doing either LOL, I know very little C/Autotools/Lua. Which is why I'm glad you're helping!

I think I'll go with https://github.com/jpe90/clp/commit/decf20da68377fd72a9fe14ebcba3a7b07a7dd86 for now and see how it pans out

Addressed by  02caec809f4994bed88b1bd81b940fb933e9b58b

**Comment by Nomarian** [comment]
should I close the PR?

**Comment by jpe90** [comment]
yeah that sounds good, and if there’s issues with 02caec8 we can reopen
