### ISSUE TITLE
Reset color at EOF

### ISSUE THREAD

**Issue by Nomarian** [jpe90/clp#7]
seems the colors overrun to the end. or maybe its all of my patches doing it.

**Comment by jpe90** [comment]
Hm, I'm not seeing it on my machine(s).. do you see it if you use a build from master?

**Comment by Nomarian** [comment]
you can test with a 


```
clp config.mk | cat /dev/stdin Makefile
```


apparently tput init should be run to reset colors. but no clue what that's doing since terminfo is gibberish to me.

**Comment by jpe90** [comment]
I see the following.. which is what is expected isn't it?

<img width="1356" alt="Screen Shot 2022-07-22 at 11 28 12 AM" src="https://user-images.githubusercontent.com/9307830/180474499-352791de-dc54-4bc0-b2cd-c2388067d531.png">

**Comment by Nomarian** [comment]
Well, no, I mean, I tend to run a shell with a PS1 that doesn't set a color, which means now the terminal is the color of whatever the last color set by clp was.


Suppose you want clp to have multiple file arguments, now the file before would run through the next one... probably?

**Comment by jpe90** [comment]
Ohh I see what you mean. I reproduced it, I'll get that fixed

**Comment by jpe90** [comment]
Does 0375446d3098407877450983c2a7bdc1e67b2910 fix it for you?

**Comment by Nomarian** [comment]
aye

**Comment by jpe90** [comment]
merged 0375446d3098407877450983c2a7bdc1e67b2910 into master
